#!/bin/bash

case $BLOCK_BUTTON in
  # 1)
esac

# Wifi
if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
    wifiicon="$(awk '/^\s*w/ { print "󰖩"}' /proc/net/wireless)"
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] ; then
    [ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ] && wifiicon="󱚼" || wifiicon="󰖪"
fi

# Ethernet
[ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ] && ethericon="󰖟" || ethericon=""

# if wired don't print wifi
if [[ ! $ethericon = "" ]] ; then
  echo "$ethericon"
else
  echo "$wifiicon"
fi
