#!/bin/bash

DMENU_OPTS="$(dmenu_pos -w 10) -l 2"

case $(echo -e "performance\\npowersave" | dmenu $DMENU_OPTS ) in
    "performance") sudo auto-cpufreq --force performance ;;
    "powersave") sudo auto-cpufreq --force powersave ;;
esac

