#!/bin/bash

DMENU_OPTS="$(dmenu_pos -w 60 -y 60) -g 6 -l 8"

chosen=$(cut -d ';' -f1 ~/.static/resources/emoji | dmenu $DMENU_OPTS | sed "s/ .*//")

[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "%s" "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
