#!/bin/bash

xrandr --output $ZK_MON_MAIN --primary --mode "${ZK_MON_WIDTH}x${ZK_MON_HEIGHT}" --rate $ZK_MON_MAIN_REFRESH --scale 1x1
xrandr --output $ZK_MON_SEC --mode $ZK_MON_SEC_RES "--${ZK_MON_SEC_POS}" $ZK_MON_MAIN --scale 1x1

nitrogen --restore
