#!/bin/bash

DMENU_OPTS="$(dmenu_pos -w 20) -l 2"

getdim() { xrandr | grep -oP '(?<=current ).*(?=,)' | tr -d ' ' ;}

updateicon() { \
	echo "$1" > /tmp/recordingicon
	pkill -RTMIN+9 "${STATUSBAR:-dwmblocks}"
}

killrecording() {
	recpid="$(cat /tmp/recordingpid)"
	kill -15 "$recpid"
	rm -f /tmp/recordingpid
	updateicon ""
	pkill -RTMIN+9 "${STATUSBAR:-dwmblocks}"
	}

video() { \
	ffmpeg -y \
	-f x11grab \
	-framerate 30 \
	-s "$(getdim)" \
	-i "$DISPLAY" \
	-r 24 \
	-use_wallclock_as_timestamps 1 \
	-f pulse -thread_queue_size 1024 -i 48 \
 	-c:v h264 \
	-crf 0 -preset ultrafast -c:a aac \
	"$ZK_DIR_RECORDING$(date '+%Y%m%d-%H%M%S')-recording.mp4" &
	echo $! > /tmp/recordingpid
	updateicon "[R]"
      	}

case "$1" in
	video) video;;
	kill) killrecording;;
	*) ([ -f /tmp/recordingpid ] && killrecording && exit) || video;;
esac
