#!/bin/bash

# echo "[!] ${2:-"Something"} executes in ${1:-"3"} seconds [!]"
echo "[!] ${2:-"Something"} [!]"

BAR="[__________________________________________________]"
STEP="#"

for n in $(seq 50); do
  BAR="${BAR/"_"/"$STEP"}"
  echo  -ne "$BAR\r"
  sleep $(echo "0.01 * ${1:-"3"}" | bc -l)
done 
echo -ne "\n"
